name: CI

# specify which github events will trigger a CI build
on: push

# define a single job 'build'
jobs:

  build:
    # specify the OS to run tests on
#    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}

    # job= sequence of steps
    steps:
    # check out repo - name = optional label
    - name: Checkout repo
      uses: actions/checkout@v4

# set up conda environment
    - name: set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        environment-file: environment.yml
        auto-activate-base: false

    - name: see content of conda environment
      run: |
        conda list

    #set up python
    - name: Set up python local version 
      uses: actions/setup-python@v4
      with: 
#        python-version: "3.10"
        python-version: ${{ matrix.python-version }}

#    - name: Install python dependencies
#      run: | 
#        python3 -m pip install --upgrade pip
#        python3 -m pip install -r requirements.txt

    - name: Test w/ pytest
      run: |
        python3 -m pytest --cov=inflammation.models tests/test_models.py 

    - name: check style w/ Pylint
      run: |
        python3 -m pylint --fail-under=0 --reports=y inflammation
