name: CI

# specify which github events will trigger a CI build
on: push

# define a single job 'build'
jobs:

  build:
    # specify the OS to run tests on
    runs-on: ubuntu-latest
    # job= sequence of steps
    steps:
    # check out repo - name = optional label
    - name: Checkout repo
      uses: actions/checkout@v4

    #set up python
    - name: Set up python 3.10
      uses: actions/setup-python@v4
      with: 
        python-version: "3.10"

    - name: Install python dependencies
      run: | 
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Test w/ pytest
      run: |
        python3 -m pytest --cov=inflammation.models tests/test_models.py 
